### PR TITLE
[NONPR-1717] Baseline prior to upgrade. Updated HMRC Resolvers to rem…

### PR DESCRIPTION
**Pull request by craigtd**
…ove Bintray. HMRC Banners added

### CODE REVIEW

**Review by Leeroyc720 — APPROVED** [review]

**Comment by craigtd** [comment]
Unit tests successful:
```
[info] All tests passed.
[info] Passed: Total 8, Failed 0, Errors 0, Passed 8
[success] Total time: 7 s, completed 20-May-2021 09:54:19
```

**Comment by craigtd** [comment]
Acceptance tests successfull
```
24 Scenarios (24 passed)
196 Steps (196 passed)
3m41.801s
```

**Review by greg-gajda — COMMENTED** [review]
Is this whole PR about changing resolvers only (not mentioning auto-generated HMRC headers)?

**Comment by craigtd** [comment]
> Is this whole PR about changing resolvers only (not mentioning auto-generated HMRC headers)?

Correct - just tidying things up as per the PR Title:
**Baseline prior to upgrade. Updated HMRC Resolvers to remove Bintray. HMRC Banners added**

**Comment by craigtd** [comment]
> Is this whole PR about changing resolvers only (not mentioning auto-generated HMRC headers)?

The pipeline also hasn't run in months - wanted a trivial change to ensure everything is working ok before dealing with breaking changes

**Pull request merged**
